AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mental-health-bot

  Sample SAM Template for mental-health-bot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  MentalHealthBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: MentalHealthBotFunction
      MemorySize: 4096
      PackageType: Image
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MentalHealthBotFunction:
    Description: "Mental Health Bot Lambda Function ARN"
    Value: !GetAtt MentalHealthBotFunction.Arn
  MentalHealthBotFunctionIamRole:
    Description: "Implicit IAM Role created for Mental Health Bot function"
    Value: !GetAtt MentalHealthBotFunctionRole.Arn
